version: '3'
services:
  app:
    build: .
    container_name: tt_development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - nodemodules:/app/node_modules

volumes:
  nodemodules: {}
